from .admin_login_page import AdminLoginPage
from .admin_main_page import AdminMainPage
from .admin_basic_category_page import AdminBasicCategoryPage
from .admin_appearance_template_page import AdminAppearanceTemplatePage
from .admin_appearance_favicon_page import AdminAppearanceFaviconPage
from .admin_catalog_page import AdminCatalogPage
from .admin_countries_page import AdminCountriesPage
from .admin_geozones_page import AdminGeozonesPage
